using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WidgetDesignerAPI.API.Migrations
{
    /// <inheritdoc />
    public partial class Fontdata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
            table: "Fonts",
            columns: new[] { "FontName", "FontClass" },
            values: new object[,]
            {
                {  "address-book", "fa fa-address-book" },
                {  "address-book-o", "fa fa-address-book-o" },
                {  "address-card", "fa fa-address-card" },
                {  "address-card-o", "fa fa-address-card-o" },
                {  "address-bandcamp", "fa fa-bandcamp" },
                {  "address-bath", "fa fa-bath" },
                {  "bathtub", "fa fa-bathtub" },
                {  "drivers-license", "fa fa-drivers-license" },
                {  "drivers-license-o", "fa fa-drivers-license-o" },
                {  "eercast", "fa fa-eercast" },
                {  "envelope-open", "envelope-fa fa-envelope-open" },
                {  "envelope-open-o", " fa fa-envelope-open-o " },
                {  "etsy", " fa fa-etsy " },
                {  "free-code-camp ", " fa fa-free-code-camp " },
                {  "handshake-o  ", " fa fa-handshake-o  " },
                {  "id-badge ", " fa fa-id-badge  " },
                {  "id-card ", " fa fa-id-card   " },
                {  "id-card-o ", " fa fa-card-o  " },
                {  "imdb  ", "  fa fa-imdb  " },
                {  "linode ", " fa fa-linode   " },
                {  "meetup ", " fa fa-meetup  " },
                {  "microchip ", " fa fa-microchip  " },
                {  "podcast ", "  fa fa-podcast    " },
                {  "quora ", " fa fa-quora  " },
                {  "ravelry ", " fa fa-ravelry   " },
                {  "s15 ", " fa fa-s15   " },
                {  "shower ", " fa fa-shower    " },
                {  "snowflake-o  ", "  fa fa-snowflake-o   " },
                {  "superpowers ", " fa fa-superpowers  " },
                {  "telegram ", " fa fa-telegram  " },
                {  "thermometer ", " fa fa-thermometer  " },
                {  "thermometer-0 ", " fa fa-thermometer-0 " },
                {  "thermometer-empty  ", " fa fa-thermometer-empty   " },
                {  "thermometer-full ", " fa fa-thermometer-full  " },
                {  "times-rectangle ", " fa fa-times-rectangle  " },
                {  "times-rectangle-o ", " fa fa-times-rectangle-o  " },
                {  "user-circle  ", " fa fa-user-circle   " },
                {  "user-circle-o  ", " fa fa-user-circle-o   " },
                {  "user-o ", "  fa fa-user-o  " },
                {  "vcard  ", " fa fa-vcard   " },
                {  "vcard-o  ", " fa fa-vcard-o  " },
                {  "window-close ", " fa fa-window-close   " },
                {  "window-close-o ", " fa fa-window-close-o   " },
                {  "window-maximize ", " fa fa-window-maximize   " },
                {  "window-minimize ", " fa fa-window-minimize  " },
                {  "window-restore ", " fa fa-window-restore  " },
                {  "wpexplorer ", " fa fa-wpexplorer  " },
                {  "address-book", "fa fa-address-book"  },
                {  "address-book-o", "fa fa-address-book-o"  },
                {  "address-card", "fa fa-address-card"  },
                {  "address-card-o", "fa fa-address-card-o"  },
                {  "adjust", "fa fa-adjust"  },
                {  "american-sign-language-interpreting", "fa fa-american-sign-language-interpreting"  },
                {  "anchor", "fa fa-anchor"  },
                {  "archive", "fa fa-archive"  },
                {  "area-chart", "fa fa-area-chart"  },
                {  "arrows", "fa fa-arrows"  },
                {  "arrows-h", "fa fa-arrows-h"  },
                {  "arrows-v", "fa fa-arrows-v"  },
                {  "asl-interpreting", "fa fa-asl-interpreting"  },
                {  "assistive-listening-systems", "fa fa-assistive-listening-systems"  },
                {  "asterisk", "fa fa-asterisk"  },
                {  "at", "fa fa-at"  },
                {  "audio-description", "fa fa-audio-description"  },
                {  "automobile", "fa fa- automobile"  },
                {  "balance-scale", "fa fa-balance-scale "  },
                {  "ban", "fa fa-ban "  },
                {  "bank", "fa fa-bank "  },
                {  "bar-chart", "fa fa-bar-chart "  },
                {  "bar-chart-o", "fa fa-bar-chart-o "  },
                {  "barcode", "fa fa-barcode "  },
                {  "bars", "fa fa-bars "  },
                {  "bath", "fa fa-bath "  },
                {  "bathtub", "fa fa-bathtub "  },
                {  "battery-0", "fa fa-battery-0 "  },
                {  "battery-1", "fa fa-battery-1 "  },
                {  "battery-2", "fa fa-battery-2 "  },
                {  "battery-3", "fa fa-battery-3 "  },
                {  "battery-4", "fa fa-battery-4 "  },
                {  "battery-empty", "fa fa-battery-empty "  },
                {  "battery-full", "fa fa-battery-full "  },
                {  "battery-half", "fa fa-battery-half"  },
                {  "battery-quarter", "fa fa-battery-quarter "  },
                {  "bed", "fa fa-bed "  },
                {  "beer", "fa fa-beer "  },
                {  "bell", "fa fa-bell "  },
                {  "bell-o", "fa fa-bell-o "  },
                {  "bell-slash", "fa fa-bell-slash "  },
                {  "bell-slash-o", "fa fa-bell-slash-o "  },
                {  "bicycle", "fa fa-bicycle "  },
                {  "binoculars", "fa fa-binoculars "  },
                {  "birthday-cake", "fa fa-birthday-cake "  },
                {  "blind", "fa fa-blind "  },
                {  "bluetooth", "fa fa-bluetooth "  },
                {  "bluetooth-b", "fa fa-bluetooth-b "  },
                {  "bolt", "fa fa-bolt "  },
                {  "bomb", "fa fa-bomb "  },
                {  "book", "fa fa-book "  },
                {  "bookmark", "fa fa-bookmark "  },
                {  "bookmark-o", "fa fa-bookmark-o "  },
                {  "braille", "fa fa-braille "  },
                {  "bug", "fa fa-bug "  },
                {  "briefcase", "fa fa-briefcase "  },
                {  "building", "fa fa-building "  },
                {  "building-o", "fa fa-building-o "  },
                {  "bullhorn", "fa fa-bullhorn "  },
                {  "bullseye", "fa fa-bullseye "  },
                {  "bus", "fa fa-bus "  },
                {  "cab", "fa fa-cab "  },
                {  "calculator", "fa fa-calculator "  },
                {  "calendar", "fa fa-calendar "  },
                {  "calendar-check-o", "fa fa-calendar-check-o "  },
                {  "calendar-minus-o", "fa fa-calendar-minus-o "  },
                {  "calendar-o", "fa fa-calendar-o "  },
                {  "calendar-plus-o", "fa fa-calendar-plus-o "  },
                {  "calendar-times-o", "fa fa-calendar-times-o "  },
                {  "camera", "fa fa-camera "  },
                {  "camera-retro", "fa fa-camera-retro "  },
                {  "car", "fa fa-car "  },
                {  "cart-arrow-down", "fa fa-cart-arrow-down "  },
                {  "cart-plus", "fa fa-cart-plus "  },
                {  "certificate", "fa fa-certificate "  },
                {  "check", "fa fa-check "  },
                {  "check-circle", "fa fa-check-circle "  },
                {  "check-square", "fa fa-check-square "  },
                {  "child", "fa fa-child "  },
                {  "circle", "fa fa-circle "  },
                {  "clock-o", "fa fa-clock-o "  },
                {  "clone", "fa fa-clone "  },
                {  "close", "fa fa-close "  },
                {  "cloud", "fa fa-cloud "  },
                {  "cloud-download", "fa fa-cloud-download "  },
                {  "cloud-upload", "fa fa-cloud-upload "  },
                {  "code", "fa fa-code "  },
                {  "code-fork", "fa fa-code-fork "  },
                {  "coffee", "fa fa-coffee "  },
                {  "cog", "fa fa-cog "  },
                {  "cogs", "fa fa-cogs "  },
                {  "comment", "fa fa-comment "  },
                {  "commenting", "fa fa-commenting"  },
                {  "comments", "fa fa-comments"  },
                {  "compass", "fa fa-compass "  },
                {  "copyright", "fa fa-copyright "  },
                {  "creative-commons", "fa fa-creative-commons "  },
                {  "credit-card", "fa fa-credit-card "  },
                {  "credit-card-alt", "fa fa-credit-card-alt "  },
                {  "crop", "fa fa-crop "  },
                {  "crosshairs", "fa fa-crosshairs "  },
                {  "cube", "fa fa-cube "  },
                {  "cubes", "fa fa-cubes "  },
                {  "cutlery", "fa fa-cutlery "  },
                {  "dashboard", "fa fa-dashboard "  },
                {  "database", "fa fa-database "  },
                {  "deaf", "fa fa-deaf "  },
                {  "deafness", "fa fa-deafness "  },
                {  "desktop", "fa fa-desktop "  },
                {  "diamond", "fa fa-diamond "  },
                {  "dot-circle-o", "fa fa-dot-circle-o "  },
                {  "download", "fa fa-download "  },
                {  "drivers-license", "fa fa-drivers-license "  },
                {  "edit", "fa fa-edit "  },
                {  "ellipsis-h", "fa fa-ellipsis-h "  },
                {  "ellipsis-v", "fa fa-ellipsis-v "  },
                {  "envelope", "fa fa-envelope "  },
                {  "envelope-open", "fa fa-envelope-open "  },
                {  "envelope-square", "fa fa-envelope-square "  },
                {  "eraser", "fa fa-eraser "  },
                {  "exchange", "fa fa-exchange "  },
                {  "exclamation", "fa fa-exclamation "  },
                {  "external-link", "fa fa-external-link "  },
                {  "eye", "fa fa-eye "  },
                {  "fax", "fa fa-fax "  },
                {  "feed", "fa fa-feed "  },
                {  "female", "fa fa-female "  },
                {  "fighter-jet", "fa fa-fighter-jet "  },
                {  "file-archive-o", "fa fa-file-archive-o "  },
                {  "file-audio-o", "fa fa-file-audio-o "  },
                {  "file-code-o", "fa fa-file-code-o "  },
                {  "file-excel-o", "fa fa-file-excel-o "  },
                {  "file-image-o", "fa fa-file-image-o "  },
                {  "file-movie-o", "fa fa-file-movie-o "  },
                {  "file-pdf-o", "fa fa-file-pdf-o "  },
                {  "file-photo-o", "fa fa-file-photo-o "  },
                {  "file-picture-o", "fa fa-file-picture-o "  },
                {  "file-powerpoint-o", "fa fa-file-powerpoint-o "  },
                {  "file-sound-o", "fa fa-file-sound-o "  },
                {  "file-video-o", "fa fa-file-video-o "  },
                {  "file-word-o", "fa fa-file-word-o "  },
                {  "file-zip-o", "fa fa-file-zip-o "  },
                {  "film", "fa fa-film "  },
                {  "filter", "fa fa-filter "  },
                {  "fire", "fa fa-fire "  },
                {  "fire-extinguisher", "fa fa-fire-extinguisher "  },
                {  "flag-checkered", "fa fa-flag-checkered "  },
                {  "flag", "fa fa-flag "  },
                {  "flash", "fa fa-flash "  },
                {  "folder", "fa fa-folder "  },
                {  "folder-o", "fa fa-folder-o "  },
                {  "folder-open", "fa fa-folder-open "  },
                {  "folder-open-o", "fa fa-folder-open-o "  },
                {  "gamepad", "fa fa-gamepad "  },
                {  "gear", "fa fa-gear "  },
                {  "gift", "fa fa-gift "  },
                {  "glass", "fa fa-glass "  },
                {  "globe", "fa fa-globe "  },
                {  "graduation-cap", "fa fa-graduation-cap "  },
                {  "group", "fa fa-group "  },
                {  "hand-grab-o", "fa fa-hand-grab-o "  },
                {  "hand-lizard-o", "fa fa-hand-lizard-o "  },
                {  "hand-paper-o", "fa fa-hand-paper-o "  },
                {  "hand-peace-o", "fa fa-hand-peace-o "  },
                {  "hand-pointer-o", "fa fa-hand-pointer-o "  },
                {  "hand-rock-o", "fa fa-hand-rock-o "  },
                {  "hand-scissors-o", "fa fa-hand-scissors-o "  },
                {  "hand-spock-o", "fa fa-hand-spock-o "  },
                {  "hand-stop-o", "fa fa-hand-stop-o "  },
                {  "handshake-o", "fa fa-handshake-o "  },
                {  "hard-of-hearing", "fa fa-hard-of-hearing "  },
                {  "hashtag", "fa fa-hashtag "  },
                {  "headphones", "fa fa-headphones "  },
                {  "heart", "fa fa-heart "  },
                {  "heartbeat", "fa fa-heartbeat "  },
                {  "history", "fa fa-history "  },
                {  "home", "fa fa-home "  },
                {  "hotel", "fa fa-hotel "  },
                {  "hourglass", "fa fa-hourglass "  },
                {  "hourglass-end", "fa fa-hourglass-end "  },
                {  "hourglass-half", "fa fa-hourglass-half "  },
                {  "hourglass-start", "fa fa-hourglass-start "  },
                {  "i-cursor", "fa fa-i-cursor "  },
                {  "id-badge", "fa fa-id-badge "  },
                {  "id-card", "fa fa-id-card "  },
                {  "id-card-o", "fa fa-id-card-o "  },
                {  "image", "fa fa-image "  },
                {  "inbox", "fa fa-inbox "  },
                {  "industry", "fa fa-industry "  },
                {  "info", "fa fa-info "  },
                {  "info-circle", "fa fa-info-circle "  },
                {  "institution", "fa fa-institution "  },
                {  "key", "fa fa-key "  },
                {  "keyboard-o", "fa fa-keyboard-o "  },
                {  "language", "fa fa-language "  },
                {  "laptop", "fa fa-laptop "  },
                {  "leaf", "fa fa-leaf "  },
                {  "legal", "fa fa-legal "  },
                {  "lemon-o", "fa fa-lemon-o "  },
                {  "level-down", "fa fa-level-down "  },
                {  "level-up", "fa fa-level-up "  },
                {  "life-bouy", "fa fa-life-bouy "  },
                {  "life-ring", "fa fa-life-ring "  },
                {  "life-saver", "fa fa-life-saver "  },
                {  "lightbulb-o", "fa fa-lightbulb-o "  },
                {  "line-chart", "fa fa-line-chart "  },
                {  "location-arrow", "fa fa-location-arrow "  },
                {  "lock", "fa fa-lock "  },
                {  "low-vision", "fa fa-low-vision "  },
                {  "magic", "fa fa-magic "  },
                {  "magnet", "fa fa-magnet "  },
                {  "mail-forward", "fa fa-mail-forward "  },
                {  "mail-reply", "fa fa-mail-reply "  },
                {  "mail-reply-all", "fa fa-mail-reply-all "  },
                {  "male", "fa fa-male "  },
                {  "map", "fa fa-map "  },
                {  "map-marker", "fa fa-map-marker "  },
                {  "map-o", "fa fa-map-o "  },
                {  "map-pin", "fa fa-map-pin "  },
                {  "map-signs", "fa fa-map-signs "  },
                {  "meh-o", "fa fa-meh-o "  },
                {  "microchip", "fa fa-microchip "  },
                {  "microphone", "fa fa-microphone "  },
                {  "minus", "fa fa-minus "  },
                {  "minus-circle", "fa fa-minus-circle "  },
                {  "minus-square", "fa fa-minus-square "  },
                {  "mobile", "fa fa-mobile "  },
                {  "mobile-phone", "fa fa-mobile-phone "  },
                {  "money", "fa fa-money "  },
                {  "moon-o", "fa fa-moon-o "  },
                {  "mortar-board", "fa fa-mortar-board "  },
                {  "motorcycle", "fa fa-motorcycle "  },
                {  "mouse-pointer", "fa fa-mouse-pointer "  },
                {  "music", "fa fa-music "  },
                {  "navicon", "fa fa-navicon "  },
                {  "newspaper-o", "fa fa-newspaper-o "  },
                {  "object-group", "fa fa-object-group "  },
                {  "object-ungroup", "fa fa-object-ungroup "  },
                {  "paint-brush", "fa fa-paint-brush "  },
                {  "paper-plane", "fa fa-paper-plane "  },
                {  "paper-plane-o", "fa fa-paper-plane-o "  },
                {  "paw", "fa fa-paw "  },
                {  "pencil", "fa fa-pencil "  },
                {  "pencil-square", "fa fa-pencil-square "  },
                {  "percent", "fa fa-percent "  },
                {  "phone", "fa fa-phone "  },
                {  "phone-square", "fa fa-phone-square "  },
                {  "photo", "fa fa-photo "  },
                {  "picture-o", "fa fa-picture-o "  },
                {  "pie-chart", "fa fa-pie-chart "  },
                {  "plane", "fa fa-plane "  },
                {  "plug", "fa fa-plug "  },
                {  "plus", "fa fa-plus "  },
                {  "plus-circle", "fa fa-plus-circle "  },
                {  "plus-square", "fa fa-plus-square "  },
                {  "plus-square-o", "fa fa-plus-square-o "  },
                {  "podcast", "fa fa-podcast "  },
                {  "power-off", "fa fa-power-off "  },
                {  "print", "fa fa-print "  },
                {  "puzzle-piece", "fa fa-puzzle-piece "  },
                {  "qrcode", "fa fa-qrcode "  },
                {  "question", "fa fa-question "  },
                {  "question-circle", "fa fa-question-circle "  },
                {  "question-circle-o", "fa fa-question-circle-o "  },
                {  "quote-left", "fa fa-quote-left "  },
                {  "quote-right", "fa fa-quote-right "  },
                {  "random", "fa fa-random "  },
                {  "recycle", "fa fa-recycle "  },
                {  "refresh", "fa fa-refresh "  },
                {  "registered", "fa fa-registered "  },
                {  "remove", "fa fa-remove "  },
                {  "reorder", "fa fa-reorder "  },
                {  "reply", "fa fa-reply "  },
                {  "reply-all", "fa fa-reply-all "  },
                {  "retweet", "fa fa-retweet "  },
                {  "road", "fa fa-road "  },
                {  "rocket", "fa fa-rocket "  },
                {  "rss", "fa fa-rss "  },
                {  "rss-square", "fa fa-rss-square "  },
                {  "search", "fa fa-search "  },
                {  "search-minus", "fa fa-search-minus "  },
                {  "search-plus", "fa fa-search-plus "  },
                {  "send", "fa fa-send "  },
                {  "send-o", "fa fa-send-o "  },
                {  "server", "fa fa-server "  },
                {  "share", "fa fa-share "  },
                {  "share-alt", "fa fa-share-alt "  },
                {  "shield", "fa fa-shield "  },
                {  "ship", "fa fa-ship "  },
                {  "shopping-bag", "fa fa-shopping-bag "  },
                {  "shopping-basket", "fa fa-shopping-basket "  },
                {  "shopping-cart", "fa fa-shopping-cart "  },
                {  "shower", "fa fa-shower "  },
                {  "sign-in", "fa fa-sign-in "  },
                {  "sign-language", "fa fa-sign-language "  },
                {  "sign-out", "fa fa-sign-out "  },
                {  "signal", "fa fa-signal "  },
                {  "signing", "fa fa-signing "  },
                {  "sitemap", "fa fa-sitemap "  },
                {  "sliders", "fa fa-sliders "  },
                {  "smile-o", "fa fa-smile-o "  },
                {  "snowflake-o", "fa fa-snowflake-o "  },
                {  "soccer-ball-o", "fa fa-soccer-ball-o "  },
                {  "sort", "fa fa-sort "  },
                {  "sort-alpha-asc", "fa fa-sort-alpha-asc "  },
                {  "sort-alpha-desc", "fa fa-sort-alpha-desc "  },
                {  "sort-amount-asc", "fa fa-sort-amount-asc "  },
                {  "sort-amount-desc", "fa fa-sort-amount-desc "  },
                {  "sort-asc", "fa fa-sort-asc "  },
                {  "sort-desc", "fa fa-sort-desc "  },
                {  "sort-down", "fa fa-sort-down "  },
                {  "sort-numeric-asc", "fa fa-sort-numeric-asc "  },
                {  "sort-numeric-desc", "fa fa-sort-numeric-desc "  },
                {  "sort-up", "fa fa-sort-up "  },
                {  "space-shuttle", "fa fa-space-shuttle "  },
                {  "spinner", "fa fa-spinner "  },
                {  "spoon", "fa fa-spoon "  },
                {  "square", "fa fa-square "  },
                {  "star", "fa fa-star "  },
                {  "star-half", "fa fa-star-half "  },
                {  "star-half-empty", "fa fa-star-half-empty "  },
                {  "star-half-full", "fa fa-star-half-full "  },
                {  "star-half-o", "fa fa-star-half-o "  },
                {  "star-o", "fa fa-star-o "  },
                {  "sticky-note", "fa fa-sticky-note "  },
                {  "sticky-note-o", "fa fa-sticky-note-o "  },
                {  "street-view", "fa fa-street-view "  },
                {  "suitcase", "fa fa-suitcase "  },
                {  "sun-o", "fa fa-sun-o "  },
                {  "support", "fa fa-support "  },
                {  "tablet", "fa fa-tablet "  },
                {  "tachometer", "fa fa-tachometer "  },
                {  "tag", "fa fa-tag "  },
                {  "tags", "fa fa-tags "  },
                {  "tasks", "fa fa-tasks "  },
                {  "taxi", "fa fa-taxi "  },
                {  "television", "fa fa-television "  },
                {  "terminal", "fa fa-terminal "  },
                {  "thermometer", "fa fa-thermometer "  },
                {  "thumb-tack", "fa fa-thumb-tack "  },
                {  "thumbs-down", "fa fa-thumbs-down "  },
                {  "thumbs-o-down", "fa fa-thumbs-o-down "  },
                {  "thumbs-o-up", "fa fa-thumbs-o-up "  },
                {  "thumbs-up", "fa fa-thumbs-up "  },
                {  "ticket", "fa fa-ticket "  },
                {  "times", "fa fa-times "  },
                {  "times-circle", "fa fa-times-circle "  },
                {  "times-rectangle", "fa fa-times-rectangle "  },
                {  "tint", "fa fa-tint "  },
                {  "toggle-down", "fa fa-toggle-down "  },
                {  "toggle-left", "fa fa-toggle-left "  },
                {  "toggle-off", "fa fa-toggle-off "  },
                {  "toggle-on", "fa fa-toggle-on "  },
                {  "toggle-right", "fa fa-toggle-right "  },
                {  "toggle-up", "fa fa-toggle-up "  },
                {  "trademark", "fa fa-trademark "  },
                {  "trash", "fa fa-trash "  },
                {  "trash-o", "fa fa-trash-o "  },
                {  "tree", "fa fa-tree "  },
                {  "trophy", "fa fa-trophy "  },
                {  "truck", "fa fa-truck "  },
                {  "tty", "fa fa-tty "  },
                {  "tv", "fa fa-tv "  },
                {  "umbrella", "fa fa-umbrella "  },
                {  "universal-access", "fa fa-universal-access "  },
                {  "university", "fa fa-university "  },
                {  "unlock", "fa fa-unlock "  },
                {  "unlock-alt", "fa fa-unlock-alt "  },
                {  "unsorted", "fa fa-unsorted "  },
                {  "upload", "fa fa-upload "  },
                {  "user", "fa fa-user "  },
                {  "user-circle", "fa fa-user-circle "  },
                {  "user-circle-o", "fa fa-user-circle-o "  },
                {  "user-o", "fa fa-user-o "  },
                {  "user-plus", "fa fa-user-plus "  },
                {  "user-secret", "fa fa-user-secret "  },
                {  "user-times", "fa fa-user-times "  },
                {  "users", "fa fa-users "  },
                {  "vcard", "fa fa-vcard "  },
                {  "vcard-o", "fa fa-vcard-o "  },
                {  "video-camera", "fa fa-video-camera "  },
                {  "volume-control-phone", "fa fa-volume-control-phone "  },
                {  "volume-down", "fa fa-volume-down "  },
                {  "volume-off", "fa fa-volume-off "  },
                {  "volume-up", "fa fa-volume-up "  },
                {  "warning", "fa fa-warning "  },
                {  "wheelchair", "fa fa-wheelchair "  },
                {  "wheelchair-alt", "fa fa-wheelchair-alt "  },
                {  "wifi", "fa fa-wifi "  },
                {  "window-close", "fa fa-window-close "  },
                {  "window-close-o", "fa fa-window-close-o "  },
                {  "window-maximize", "fa fa-window-maximize "  },
                {  "window-minimize", "fa fa-window-minimize "  },
                {  "window-restore", "fa fa-window-restore "  },
                {  "wrench", "fa fa-wrench "  },


            });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
